FROM ghcr.io/dependabot/dependabot-updater-pip:v2.0.20250410131606@sha256:e0a2d50af94d2b85aa52eb03bcda9f4bdd8f4937817a1e060e90f0de00c7336e

RUN apt-get update && apt-get install -y ca-certificates curl python3 python3-pip
RUN python3 -m pip install --upgrade pip && python3 -m pip install requests
RUN useradd dependabot && chgrp dependabot /etc/ssl/certs && chmod g+w /etc/ssl/certs
ENV REQUESTS_CA_BUNDLE=/etc/ssl/certs/ca-certificates.crt

COPY --chown=dependabot --chmod=755 run bin/run

-- run --
#!/usr/bin/env bash

python3 --version
python3 -c 'import requests; requests.get("https://pypi.org")'