#!/bin/sh -e

ROOT=$(dirname "$0")/..
export ROOT

cd $ROOT
npm run build
npm run package

GITHUB_EVENT_NAME=repository_dispatch \
  GITHUB_EVENT_PATH="${ROOT}/script/hack-event.json" \
  node dist/index.js
