name: Check dist

on:
  pull_request:
  push:
    branches:
      - main
      - 'releases/*'

permissions:
  contents: read
jobs:
  verify-build: # make sure the checked in dist/ folder matches the output of a rebuild
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version-file: .nvmrc
          cache: 'npm'

      - run: npm clean-install

      - name: Rebuild the dist/ directory
        run: npm run package

      - name: Compare the expected and actual dist/ directories
        run: script/check-diff
  verify-index-js: # make sure the entrypoint js files run on a clean machine without compiling first
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - uses: ./
        with:
          milliseconds: 1000
